In [4]:
import numpy as np
import pandas as pd
import os
import cv2
import sklearn.svm as svm

In [5]:
class_paths = ['./svm/train/0', './svm/train/1', './svm/train/2', 
               './svm/train/3', './svm/train/4', './svm/train/5']
images = [[] for i in range(6)]
for i  in range(len(class_paths)):
    for filename in os.listdir(class_paths[i]):
        img = cv2.imread(os.path.join(class_paths[i], filename))
        if img is not None:
            resized_img = cv2.resize(img, (16, 16))
            normalized_img = resized_img / 255.0
            flattened_img = normalized_img.flatten()
            images[i].append(flattened_img)

In [7]:
validation_paths = ['./svm/val/0', './svm/val/1', './svm/val/2', 
                    './svm/val/3', './svm/val/4', './svm/val/5']
validation_images = [[] for i in range(6)]
for i  in range(len(validation_paths)):
    for filename in os.listdir(validation_paths[i]):
        img = cv2.imread(os.path.join(validation_paths[i], filename))
        if img is not None:
            resized_img = cv2.resize(img, (16, 16))
            normalized_img = resized_img / 255.0
            flattened_img = normalized_img.flatten()
            validation_images[i].append(flattened_img)

In [8]:
X = np.array(images[0] + images[1] + images[2] + images[3] + images[4] + images[5])
Y = np.array([0] * len(images[0]) + [1] * len(images[1]) + [2] * len(images[2]) + [3]*len(images[3]) + [4]*len(images[4]) + [5]*len(images[5]))

In [9]:
svm_skl = svm.SVC(kernel='rbf', C=1.0, decision_function_shape='ovo')
svm_skl.fit(X, Y)

SVC(decision_function_shape='ovo')

In [13]:
svm_valid_correct = 0
svm_valid_incorrect = 0
misclassified = []
misclassified_class = [[] for i in range(6)]
misclassified_prediction = [[] for i in range(6)]
svm_confusion_matrix = np.zeros((6, 6))
for i in range(len(validation_images)):
    print(f"Starting validation for class {i}")
    j = 0
    for img in validation_images[i]:
        print(j, end=' ')
        prediction = svm_skl.predict([img])[0]
        svm_confusion_matrix[i][prediction] += 1
        if prediction == i:
            svm_valid_correct += 1
        else:
            svm_valid_incorrect += 1
            misclassified.append(img)
            misclassified_class[i].append(j)
            misclassified_prediction[i].append(prediction)
        j += 1
    print()

Starting validation for class 0
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 
Starting validation for class 1
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 

In [14]:
print(f"Correct: {svm_valid_correct}\nIncorrect: {svm_valid_incorrect}\nAccuracy: {svm_valid_correct / (svm_valid_correct + svm_valid_incorrect)}")
print(f"Confusion Matrix:\n{svm_confusion_matrix}")

Correct: 781
Incorrect: 419
Accuracy: 0.6508333333333334
Confusion Matrix:
[[116.  15.  17.  16.   8.  28.]
 [  7. 154.   0.   3.   7.  29.]
 [ 12.   1. 139.  19.  21.   8.]
 [ 19.   5.  21. 125.  26.   4.]
 [ 20.   8.  37.  29. 104.   2.]
 [ 31.  12.   7.   6.   1. 143.]]
